### ISSUE TITLE
Link to footer Issue

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#71] opened 2016-08-19 16:54 UTC
Add footer as indicated in #61

**Comment by nathan-omaorg** [comment] 2016-08-23 16:19
Duplicate of #61.

I'm not sure why this issue was created?

**Comment by github-oma** [comment] 2016-08-23 19:20
When we discussed to classified the issues in Milestones, @nathan-omaorg indicated that we will need to duplicate the issues for each Milestone. It is not possible to allocate an Issue to multiple Milestones. They only way to do it is to create an Issue for each Milestone. In this way we know what is the work that has to be done. What I believe that we don't need to do it is to allocate it to you as long it has been done already once.

**Comment by nathan-omaorg** [comment] 2016-08-24 11:17
Fixed in DevMaster

**Closed** 2016-08-24 11:17 UTC
Labels: duplicate, enhancement
